import '../../domain/entities/attendance.dart' as entities;
import '../../domain/entities/attendance_status.dart' as entities;
import '../../domain/repositories/attendance_repository.dart' as repositories;
import '../datasources/attendance_remote_datasource.dart' as datasources;

class AttendanceRepositoryImpl implements repositories.AttendanceRepository {
  final datasources.AttendanceRemoteDataSource remoteDataSource;

  AttendanceRepositoryImpl({required this.remoteDataSource});

  @override
  Future<entities.AttendanceStatus> checkAttendanceStatus() async {
    final result = await remoteDataSource.checkAttendanceStatus();

    return entities.AttendanceStatus(
      isInOfficeArea: result['isInOfficeArea'] as bool,
      hasFaceData: result['hasFaceData'] as bool,
      distanceInMeters: result['distanceInMeters'] as double?,
      message: '', // Will be generated by entity
    );
  }

  @override
  Future<void> recordAttendance({required String type}) async {
    await remoteDataSource.recordAttendance(type: type);
  }

  @override
  Future<List<entities.Attendance>> getAttendanceHistory() async {
    return await remoteDataSource.getAttendanceHistory();
  }
}
