import '../../domain/entities/attendance.dart' as entities;
import '../../domain/entities/attendance_status.dart' as entities;
import '../../domain/repositories/attendance_repository.dart' as repositories;
import '../datasources/attendance_remote_datasource.dart' as datasources;

import '../../../../core/services/session_service.dart';

class AttendanceRepositoryImpl implements repositories.AttendanceRepository {
  final datasources.AttendanceRemoteDataSource remoteDataSource;
  final SessionService sessionService;

  AttendanceRepositoryImpl({
    required this.remoteDataSource,
    required this.sessionService,
  });

  @override
  Future<entities.AttendanceStatus> checkAttendanceStatus() async {
    final user = await sessionService.getSession();
    if (user == null) throw Exception('User session not found');

    final result = await remoteDataSource.checkAttendanceStatus(uid: user.uid);

    return entities.AttendanceStatus(
      isInOfficeArea: result['isInOfficeArea'] as bool,
      hasFaceData: result['hasFaceData'] as bool,
      distanceInMeters: result['distanceInMeters'] as double?,
      message: '', // Will be generated by entity
    );
  }

  @override
  Future<void> recordAttendance({required String type}) async {
    final user = await sessionService.getSession();
    if (user == null) throw Exception('User session not found');

    await remoteDataSource.recordAttendance(
      uid: user.uid,
      email: user.email,
      type: type,
    );
  }

  @override
  Future<List<entities.Attendance>> getAttendanceHistory() async {
    final user = await sessionService.getSession();
    if (user == null) throw Exception('User session not found');

    return await remoteDataSource.getAttendanceHistory(uid: user.uid);
  }

  @override
  Future<Map<String, dynamic>?> getTodayAttendance() async {
    final user = await sessionService.getSession();
    if (user == null) throw Exception('User session not found');

    return await remoteDataSource.getTodayAttendance(uid: user.uid);
  }
}
