// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJzwYhTqripxVUY6Md5xqksdNM_3Ycnk',
    appId: '1:424930002187:web:746161511af30f2dc7ce0e',
    messagingSenderId: '424930002187',
    projectId: 'absensi-pegawai-app',
    authDomain: 'absensi-pegawai-app.firebaseapp.com',
    storageBucket: 'absensi-pegawai-app.firebasestorage.app',
    measurementId: 'G-GBQKN3F642',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByNV0hkS6We9W5_tszRUcjW9S9iIDRsI',
    appId: '1:424930002187:android:4a7c71f052711df0c7ce0e',
    messagingSenderId: '424930002187',
    projectId: 'absensi-pegawai-app',
    storageBucket: 'absensi-pegawai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_5z92WaTHu7JOxNwyrCDGvQUyuJ7EAXE',
    appId: '1:424930002187:ios:fb74814913690b67c7ce0e',
    messagingSenderId: '424930002187',
    projectId: 'absensi-pegawai-app',
    storageBucket: 'absensi-pegawai-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTugas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_5z92WaTHu7JOxNwyrCDGvQUyuJ7EAXE',
    appId: '1:424930002187:ios:fb74814913690b67c7ce0e',
    messagingSenderId: '424930002187',
    projectId: 'absensi-pegawai-app',
    storageBucket: 'absensi-pegawai-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppTugas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJzwYhTqripxVUY6Md5xqksdNM_3Ycnk',
    appId: '1:424930002187:web:f7338c0fbbb51945c7ce0e',
    messagingSenderId: '424930002187',
    projectId: 'absensi-pegawai-app',
    authDomain: 'absensi-pegawai-app.firebaseapp.com',
    storageBucket: 'absensi-pegawai-app.firebasestorage.app',
    measurementId: 'G-R3NTBP3WPQ',
  );

}